name = "Registry.jl"
uuid = "58b2901e-23a2-40be-a278-98689d155278"
repo = "https://github.com/Davide-Lasagna-s-Lab/Registry.jl"

[packages]
28eb41cd-435a-4ede-8bdb-f2685fc03e8c = { name = "FDGrids", path = "F/FDGrids" }
2cb43c6e-2c58-11e9-183a-2725e2c9802c = { name = "OpenKolmogorovFlow", path = "O/OpenKolmogorovFlow" }
53bbc39a-2c58-11e9-14b8-a5180f719d78 = { name = "NKSearch", path = "N/NKSearch" }
5c307136-fb89-411d-b568-fbf16049e5ad = { name = "ChebUtils", path = "C/ChebUtils" }
701a43e8-2c5a-11e9-2d86-e5d483bb0ff0 = { name = "GMRES", path = "G/GMRES" }
9778a910-ce4d-423e-92be-12991f0cf10c = { name = "NSEBase", path = "N/NSEBase" }
a88878f4-81de-4718-8ef2-0d5b47c6289d = { name = "Continuation", path = "C/Continuation" }
a8e3295d-89e8-4b4f-a448-5f2c64bcc7b5 = { name = "FDHelmoltzSolver", path = "F/FDHelmoltzSolver" }
b2c17008-295b-4fcf-b5c4-ce68318043a5 = { name = "ReSolverChannelFlowMP", path = "R/ReSolverChannelFlowMP" }
c724298d-75c1-46c2-b795-cd153ae6310d = { name = "NSEBaseMPIExt", path = "N/NSEBaseMPIExt" }
cbbec004-2816-4a06-900b-d51f11be72b6 = { name = "ReSolverChannelFlowGPU", path = "R/ReSolverChannelFlowGPU" }
d910d432-2c57-11e9-263c-df934de6853d = { name = "Flows", path = "F/Flows" }
ea847659-7271-4841-b0fc-79dd10df6815 = { name = "ReSolverChannelFlow", path = "R/ReSolverChannelFlow" }
